loyalty:
  service:
    port: 8050
    image:
      name: rybkiny/loyalty
      version: "latest"
    database:
      url: "jdbc:postgresql://postgres:5432/loyalties"
payment:
  service:
    port: 8060
    image:
      name: rybkiny/payment
      version: "latest"
    database: 
      url: "jdbc:postgresql://postgres:5432/payments"
reservation:
  service:
    port: 8070
    image:
      name: rybkiny/reservation
      version: "latest"
    database: 
      url: "jdbc:postgresql://postgres:5432/reservations"
gateway:
  service:
    port: 8080
    image:
      name: rybkiny/gateway
      version: "latest"
    isGateway: true